# Change these first
owner: Certania # Your GitHub organization or username, where this repository lives
repo: status-website # The name of this repository

sites:
  - name: CERTANIA
    url: https://certania.com
  ## LIFE SCIENCES
  - name: ALPHALYTIK
    url: https://www.alphalytik.com/
  - name: DINOX
    url: https://www.dinox.de/
  - name: GBD
    url: https://www.gbd-biotechdia.com/
  - name: ÖHMI Pharma
    url: https://www.oehmi-analytik.de/leistungen/pharma-und-umweltlabor
  - name: SOCRAMETRICS
    url: https://socrametrics.com/
  - name: SOCRATEC R&D
    url: https://socratec-pharma.de/
  - name: SPINESERV
    url: https://www.spineserv.de/
  ## FOOD & ENVIRONMENT
  - name: BIOTEC
    url: https://www.biotec-gmbh.com/
  - name: BIOTESYS
    url: https://biotesys.de/
  - name: ELAB-ANALYTIK
    url: https://elab-analytik.de/
  - name: FSI HEALTH & SAFETY​
    url: https://fsi.de/
  - name: INSTITUT DR. NUSS
    url: https://www.institut-nuss.de/
  - name: LABOSPORT
    url: https://labosport.com/
  - name: ÖHMI ANALYTIK
    url: https://www.oehmi-analytik.de
  - name: SGI COMPLIANCE​
    url: https://sgicompliance.com/
  - name: TRISKELION
    url: https://www.triskelion.nl/
  ## ESG & ANALYTICS
  - name: DFGE
    url: https://dfge.de/
  - name: NATUREOFFICE
    url: https://natureoffice.com/
  ## CERTIFICATION & VERIFICATION
  - name: CERTURIA
    url: https://www.certuria.de/
  - name: IFU CERT
    url: https://www.ifu-cert.de/  
  - name: ÖHMI EUROCERT
    url: https://www.oehmi-cert.de/de/
  ## MATERIALS & STRUCTURES
  - name: FIATEC
    url: https://www.fiatec.com/
  - name: GWP
    url: https://gwp.eu/
  - name: KÖTTER
    url: https://koetter-consulting.com/
  - name: MPR
    url: https://www.mpr-international.com/
  - name: ÖHMI SERVICE
    url: https://www.oehmi-service.de/
  - name: RELIBELL
    url: https://www.relibell.de/
  - name: SPC
    url: https://spc-lab.de/
  - name: TAZ
    url: https://tazgmbh.de/

    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-website
  theme: light
  logoUrl: https://avatars.githubusercontent.com/u/156069591?s=200&v=4
  name: CERTANIA Partners Status Board
  introTitle: "Dashboard for monitoring all partner pages"
  introMessage: We collect response time information about all partner pages to adjust measures optimizing the sites for our customers.
  favicon: https://certania.com/img/favicons/favicon-32x32.png
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: CERTANIA
      href: https://certania.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
